### ISSUE TITLE
webcomponents.min.js is empty in dist folder

### ISSUE THREAD

**Issue by chuckh** [yeoman/generator-polymer#171] opened 2015-04-10 14:56 UTC
After doing a grunt build, the webcomponents.min.js file is empty in the /dist/bower_components/webcomponentsjs/. I am using v0.7.2.

As a work around after doing grunt build I do this:
cp bower_components/webcomponentsjs/webcomponents.min.js dist/bower_components/webcomponentsjs/webcomponents.min.js

**Comment by ragingwind** [comment] 2015-04-13 12:01
All of files under bower_components should be [copied](https://github.com/yeoman/generator-polymer/blob/master/app/templates/Gruntfile.js#L251) to dist by `copy:dist` task. how about other packages? just webcomponentjs wasn't copied?

**Comment by bereciartua** [comment] 2015-04-13 13:16
I have the same issue using grunt.
The file /dist/bower_components/webcomponentsjs/webcomponents.min.js is there but empty.
I couldn't find where it's broken.

**Comment by arthurvr** [comment] 2015-05-04 18:35
@chuckh @bereciartua Did the other files copy?

**Comment by chuckh** [comment] 2015-05-04 19:56
Yes the other files copied. A file of webcomponents.min.js with zero bytes was created.

My workaround for now is after running grunt build I do:

```cp bower_components/webcomponentsjs/webcomponents.min.js dist/bower_components/webcomponentsjs/webcomponents.min.js```

**Comment by nbellocam** [comment] 2015-05-18 00:10
This issue is caused by the useminPrepare:html task.

If you see the `grunt --verbose` output task you will see the following (note the `bower_components/webcomponentsjs/webcomponents.js` path which is located inside the app folder instead of being in the root folder):

```
Running "useminPrepare:html" (useminPrepare) task
Verifying property useminPrepare.html exists in config...OK
Files: app/index.html -> html
Options: dest="dist"
Going through app/index.html to update the config
Looking for build script HTML comment blocks

Configuration is now:

  concat:
  { generated: 
   { files: 
      [ { dest: '.tmp/concat/styles/main.css',
          src: [ 'app/styles/main.css' ] },
        { dest: '.tmp/concat/bower_components/webcomponentsjs/webcomponents.min.js',
          src: [ 'app/bower_components/webcomponentsjs/webcomponents.js' ] },
        { dest: '.tmp/concat/scripts/app.js',
          src: [ 'app/scripts/app.js' ] } ] } }

  uglify:
  { generated: 
   { files: 
      [ { dest: 'dist/bower_components/webcomponentsjs/webcomponents.min.js',
          src: [ '.tmp/concat/bower_components/webcomponentsjs/webcomponents.min.js' ] },
        { dest: 'dist/scripts/app.js',
          src: [ '.tmp/concat/scripts/app.js' ] } ] } }
```

By adding `(.)` as part of the build declaration in the index.html template file this issue is fixed. You can see more information about setting an _alternate search path_ at https://github.com/yeoman/grunt-usemin#blocks.

```<!-- build:js(.) bower_components/webcomponentsjs/webcomponents.min.js -->```

I created pull request https://github.com/yeoman/generator-polymer/pull/182 with this fix.

However, note that the _uglify_ task is minifying the minified file (from  255.22 kB to 115.68 kB), I don't know if this is what you want.

**Comment by robdodson** [comment] 2015-06-08 01:14
Closing this as the generator is now based on [Polymer Starter Kit](https://github.com/PolymerElements/polymer-starter-kit).

**Closed by robdodson** 2015-06-08 01:14 UTC
