### ISSUE TITLE
Drop CoffeeScript in favor of ES6 (Babel)

### ISSUE THREAD

**Issue by silvenon** [yeoman/generator-polymer#193] opened 2015-06-13 16:19 UTC
Ref. https://github.com/yeoman/generator-webapp/pull/543#issuecomment-111724489.

**Comment by arthurvr** [comment] 2015-06-13 16:20
We don't have coffeescript. Also this is a duplicate of https://github.com/yeoman/generator-polymer/issues/181.

**Closed by arthurvr** 2015-06-13 16:20 UTC
